import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://map.chronicle.rip/")
    expect(page.get_by_test_id("toolbar-a-1")).to_be_visible()
    expect(page.get_by_test_id("autocomplete-base-routing-div-search-field")).to_be_visible()
    expect(page.get_by_role("button", name="ADVANCED")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-about-chronicle")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("toolbar-a-mat-focus-indicator").click()
    expect(page.get_by_test_id("login-login-screen-img-logo")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-h2-sign-in-text")).to_be_visible()
    expect(page.locator("div").filter(has_text=re.compile(r"^Email \*$"))).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Email \*$")).click()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").fill("faris+astanaorg@chronicle.rip")
    expect(page.locator("div").filter(has_text=re.compile(r"^Password \*$"))).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Password \*$")).click()
    page.get_by_test_id("login-mat-form-field-input-password").fill("12345")
    expect(page.get_by_test_id("login-login-screen-div-remember-me").get_by_text("Remember me")).to_be_visible()
    page.get_by_test_id("login-login-screen-div-remember-me").get_by_text("Remember me").click()
    expect(page.get_by_test_id("login-login-screen-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("login-login-screen-button-mat-focus-indicator").click()
    page.goto("https://aus.chronicle.rip/customer-organization/Astana_Tegal_Gundul")
    expect(page.get_by_test_id("customer-organization-autocomplete-base-routing-div-search-field")).to_be_visible()
    expect(page.get_by_role("button", name="Advanced")).to_be_visible()
    expect(page.get_by_role("button", name="Notifications")).to_be_visible()
    expect(page.get_by_role("button", name="Astana Tegal Gunduls faris+")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-side-menu-section-sectionId")).to_be_visible()
    expect(page.get_by_role("button", name="Tables")).to_be_visible()
    page.get_by_role("button", name="Tables").click()
    expect(page.get_by_role("button", name="FILTER")).to_be_visible()
    expect(page.get_by_role("button", name="EXPORT")).to_be_visible()
    expect(page.get_by_role("button", name="ADD PLOT")).to_be_visible()
    expect(page.locator("a").filter(has_text="BUSINESS")).to_be_visible()
    expect(page.locator("a").filter(has_text="PERSONS")).to_be_visible()
    expect(page.locator("a").filter(has_text="ROISX")).to_be_visible()
    expect(page.locator("a").filter(has_text="INTERMENTS")).to_be_visible()
    page.locator("a").filter(has_text="INTERMENTS").click()
    expect(page.get_by_role("button", name="ADD INTERMENTS")).to_be_visible()
    expect(page.get_by_role("button", name="EXPORT")).to_be_visible()
    expect(page.get_by_role("button", name="FILTER")).to_be_visible()
    page.get_by_role("button", name="FILTER").click()
    expect(page.get_by_test_id("customer-organization-advance-table-mat-dialog-container-h2-mat-dialog-title")).to_be_visible()
    expect(page.locator("div").filter(has_text=re.compile(r"^Section$")).nth(2)).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Section$")).nth(2).click()
    page.locator("div").filter(has_text=re.compile(r"^Section$")).nth(2).click()
    page.get_by_role("option", name="A").click()
    expect(page.locator("div").filter(has_text=re.compile(r"^Row$")).nth(2)).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Row$")).nth(2).click()
    page.get_by_placeholder("Row").fill("Z")
    expect(page.get_by_role("button", name="APPLY")).to_be_visible()
    page.get_by_role("button", name="APPLY").click()
    expect(page.get_by_role("gridcell", name="Kirito")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Kazuto")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Budi Santoso Wijaya")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Agus Setiawan Pratama")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Rumah Duka Sejahtera")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Masjid Raya Bandung")).to_be_visible()
    page.get_by_role("gridcell", name="Kirito").click()
    expect(page.get_by_role("heading", name="Edit Interment")).to_be_visible()
    expect(page.get_by_role("button", name="Deceased person")).to_be_visible()
    expect(page.get_by_role("button", name="Interment details")).to_be_visible()
    expect(page.get_by_role("button", name="Story")).to_be_visible()
    expect(page.get_by_role("button", name="Documents")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-a20z202-manage-edit-interment-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-a20z202-manage-edit-interment-toolbar-manage-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-a20z202-manage-edit-interment-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-a20z202-manage-edit-interment-toolbar-manage-button-mat-focus-indicator").click()
    expect(page.get_by_role("button", name="Delete")).to_be_visible()
    page.get_by_role("button", name="Delete").click()
    expect(page.get_by_role("heading", name="Delete Interment")).to_be_visible()
    expect(page.get_by_text("This action cannot be undone.")).to_be_visible()
    expect(page.get_by_role("button", name="CANCEL")).to_be_visible()
    expect(page.get_by_role("button", name="DELETE")).to_be_visible()
    page.get_by_role("button", name="DELETE").click()
    expect(page.get_by_role("heading", name="This plot is empty")).to_be_visible()
    expect(page.get_by_text("Would you like to keep the")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-a20z202-manage-edit-interment-last-interment-dialog-button-no-option")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-a20z202-manage-edit-interment-last-interment-dialog-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-a20z202-manage-edit-interment-last-interment-dialog-button-mat-focus-indicator").click()
    expect(page.get_by_text("Interment record removed")).to_be_visible()
    expect(page.get_by_text("INTERMENTS 0")).to_be_visible()
