import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://map.chronicle.rip/")
    expect(page.get_by_test_id("toolbar-a-1")).to_be_visible()
    expect(page.get_by_role("button", name="ADVANCED")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("toolbar-a-mat-focus-indicator").click()
    expect(page.get_by_test_id("login-login-screen-img-logo")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-h2-sign-in-text")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-div-under-button").get_by_test_id("login-login-screen-a-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-div-sign-up-info").get_by_test_id("login-login-screen-a-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_test_id("login-mat-form-field-input-mat-input-element")).to_be_visible()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").click()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").fill("faris+astanaorg@chronicle.rip")
    expect(page.get_by_test_id("login-mat-form-field-input-password")).to_be_visible()
    page.get_by_test_id("login-mat-form-field-input-password").click()
    page.get_by_test_id("login-mat-form-field-input-password").fill("12345")
    expect(page.locator(".mat-checkbox-inner-container")).to_be_visible()
    page.locator(".mat-checkbox-inner-container").click()
    expect(page.get_by_test_id("login-login-screen-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("login-login-screen-button-mat-focus-indicator").click()
    page.goto("https://aus.chronicle.rip/customer-organization/Astana_Tegal_Gundul")
    expect(page.get_by_test_id("customer-organization-chronicle-admin-organization-toolbar-div-business-name-org")).to_be_visible()
    expect(page.get_by_role("button", name="Astana Tegal Gunduls faris+")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-perfect-scrollbar-h3-cemetery-name")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-perfect-scrollbar-button-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-side-menu-section-sectionId")).to_be_visible()
    expect(page.get_by_role("button", name="Tables")).to_be_visible()
    page.get_by_role("button", name="Tables").click()
    expect(page.get_by_test_id("customer-organization-advance-table-select-search-cemetery-div-global-cem-select-label")).to_be_visible()
    expect(page.get_by_text("PLOTS 186")).to_be_visible()
    expect(page.locator("a").filter(has_text="INTERMENTS")).to_be_visible()
    expect(page.locator("a").filter(has_text="ROIS")).to_be_visible()
    expect(page.locator("a").filter(has_text="PERSONS")).to_be_visible()
    expect(page.locator("a").filter(has_text="BUSINESS")).to_be_visible()
    page.locator("a").filter(has_text="INTERMENTS").click()
    expect(page.get_by_text("INTERMENTS 19")).to_be_visible()
    expect(page.get_by_role("gridcell", name="A A 3")).to_be_visible()
    expect(page.get_by_role("gridcell", name="kirito")).to_be_visible()
    expect(page.get_by_role("gridcell", name="wijaya", exact=True)).to_be_visible()
    page.get_by_role("gridcell", name="A A 3").click()
    expect(page.get_by_role("heading", name="Edit Interment")).to_be_visible()
    expect(page.get_by_role("heading", name="Astana Tegal Gundul - A A")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-interment-edit-form-span-edit-plot")).to_be_visible()
    expect(page.get_by_role("button", name="Deceased person")).to_be_visible()
    expect(page.get_by_role("button", name="Interment details")).to_be_visible()
    expect(page.get_by_role("button", name="Story")).to_be_visible()
    expect(page.get_by_role("button", name="Documents")).to_be_visible()
    page.get_by_role("button", name="Deceased person").click()
    expect(page.get_by_role("textbox", name="Middle name")).to_be_visible()
    page.get_by_role("textbox", name="Middle name").click()
    page.get_by_role("textbox", name="Middle name").fill("saputra")
    expect(page.get_by_role("button", name="save")).to_be_visible()
    page.get_by_role("button", name="save").click()
    page.goto("https://aus.chronicle.rip/customer-organization/advance-table?tab=interments")
    expect(page.get_by_role("alert")).to_be_visible()
    expect(page.get_by_text("Data saved successfully")).to_be_visible()
    expect(page.get_by_role("gridcell", name="A A 3")).to_be_visible()
    expect(page.get_by_role("gridcell", name="kirito")).to_be_visible()
    expect(page.get_by_role("gridcell", name="saputra", exact=True)).to_be_visible()
    expect(page.get_by_role("gridcell", name="wijaya", exact=True)).to_be_visible()
