import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://map.chronicle.rip/")
    expect(page.get_by_test_id("toolbar-a-1")).to_be_visible()
    expect(page.get_by_role("button", name="ADVANCED")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("toolbar-a-mat-focus-indicator").click()
    expect(page.get_by_test_id("login-login-screen-img-logo")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-h2-sign-in-text")).to_be_visible()
    expect(page.get_by_text("Or use Chronicle account")).to_be_visible()
    expect(page.get_by_test_id("login-mat-form-field-input-mat-input-element")).to_be_visible()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").click()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").fill("faris+astanaorg@chronicle.rip")
    expect(page.get_by_test_id("login-mat-form-field-input-password")).to_be_visible()
    page.get_by_test_id("login-mat-form-field-input-password").click()
    page.get_by_test_id("login-mat-form-field-input-password").fill("12345")
    expect(page.locator(".mat-checkbox-inner-container")).to_be_visible()
    page.locator(".mat-checkbox-inner-container").click()
    expect(page.get_by_test_id("login-login-screen-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("login-login-screen-button-mat-focus-indicator").click()
    page.goto("https://aus.chronicle.rip/customer-organization/Astana_Tegal_Gundul")
    expect(page.get_by_test_id("customer-organization-chronicle-admin-organization-toolbar-div-business-name-org")).to_be_visible()
    expect(page.get_by_role("button", name="Advanced")).to_be_visible()
    expect(page.get_by_role("button", name="Astana Tegal Gunduls faris+")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-side-menu-section-sectionId")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-perfect-scrollbar-button-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_role("button", name="Tables")).to_be_visible()
    page.get_by_role("button", name="Tables").click()
    expect(page.get_by_test_id("customer-organization-advance-table-select-search-cemetery-div-global-cem-select-label")).to_be_visible()
    expect(page.get_by_role("button", name="FILTER")).to_be_visible()
    expect(page.get_by_role("button", name="ADD PLOT")).to_be_visible()
    expect(page.get_by_text("PLOTS 186")).to_be_visible()
    expect(page.get_by_role("button", name="ADD PLOT")).to_be_visible()
    page.get_by_role("button", name="ADD PLOT").click()
    expect(page.get_by_role("heading", name="Add plot")).to_be_visible()
    expect(page.get_by_role("button", name="save")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-advance-table-manage-add-plot-mat-form-field-input-type-your-section-name")).to_be_visible()
    page.get_by_test_id("customer-organization-advance-table-manage-add-plot-mat-form-field-input-type-your-section-name").click()
    page.get_by_text("A close").click()
    expect(page.get_by_test_id("customer-organization-advance-table-manage-add-plot-plot-add-div-plot-position").get_by_test_id("customer-organization-advance-table-manage-add-plot-mat-form-field-input-mat-input-element")).to_be_visible()
    page.get_by_test_id("customer-organization-advance-table-manage-add-plot-plot-add-div-plot-position").get_by_test_id("customer-organization-advance-table-manage-add-plot-mat-form-field-input-mat-input-element").click()
    page.get_by_test_id("customer-organization-advance-table-manage-add-plot-plot-add-div-plot-position").get_by_test_id("customer-organization-advance-table-manage-add-plot-mat-form-field-input-mat-input-element").fill("Z")
    expect(page.get_by_test_id("customer-organization-advance-table-manage-add-plot-plot-add-div-plot-position").get_by_test_id("customer-organization-advance-table-manage-add-plot-mat-form-field-input-number")).to_be_visible()
    page.get_by_test_id("customer-organization-advance-table-manage-add-plot-plot-add-div-plot-position").get_by_test_id("customer-organization-advance-table-manage-add-plot-mat-form-field-input-number").click()
    page.get_by_test_id("customer-organization-advance-table-manage-add-plot-plot-add-div-plot-position").get_by_test_id("customer-organization-advance-table-manage-add-plot-mat-form-field-input-number").fill("1")
    expect(page.locator(".mat-select-placeholder").first).to_be_visible()
    page.locator(".mat-select-placeholder").first.click()
    page.get_by_text("Occupied").click()
    expect(page.locator(".mat-select-placeholder").first).to_be_visible()
    page.locator(".mat-select-placeholder").first.click()
    page.get_by_text("Cremation", exact=True).click()
    expect(page.get_by_role("button", name="save")).to_be_visible()
    page.get_by_role("button", name="save").click()
    expect(page.get_by_test_id("customer-organization-advance-table-mat-sidenav-content-div-table-wrapper").get_by_text("A Z")).to_be_visible()
