import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://map.chronicle.rip/")
    expect(page.get_by_test_id("toolbar-a-1")).to_be_visible()
    expect(page.get_by_role("button", name="ADVANCED")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("toolbar-a-mat-focus-indicator").click()
    expect(page.get_by_test_id("login-login-screen-h2-sign-in-text")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-button-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_test_id("login-mat-form-field-input-mat-input-element")).to_be_visible()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").click()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").fill("faris+astanaorg@chronicle.rip")
    expect(page.get_by_test_id("login-mat-form-field-input-password")).to_be_visible()
    page.get_by_test_id("login-mat-form-field-input-password").click()
    page.get_by_test_id("login-mat-form-field-input-password").fill("12345")
    expect(page.get_by_test_id("login-login-screen-button-mat-focus-indicator")).to_be_visible()
    expect(page.locator(".mat-checkbox-inner-container")).to_be_visible()
    page.locator(".mat-checkbox-inner-container").click()
    expect(page.get_by_test_id("login-login-screen-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("login-login-screen-button-mat-focus-indicator").click()
    page.goto("https://aus.chronicle.rip/customer-organization/Astana_Tegal_Gundul")
    expect(page.get_by_test_id("customer-organization-chronicle-admin-organization-toolbar-div-business-name-org")).to_be_visible()
    expect(page.get_by_role("button", name="Astana Tegal Gunduls faris+")).to_be_visible()
    expect(page.get_by_role("button", name="Advanced")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-perfect-scrollbar-button-mat-focus-indicator")).to_be_visible()
    page.get_by_role("button", name="Advanced").click()
    expect(page.get_by_role("textbox", name="Plot ID")).to_be_visible()
    page.get_by_role("textbox", name="Plot ID").click()
    page.get_by_role("textbox", name="Plot ID").fill("B G 12")
    expect(page.get_by_role("button", name="SEARCH")).to_be_visible()
    page.get_by_role("button", name="SEARCH").click()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-search-advance-advance-search-result-span-name")).to_be_visible()
    expect(page.get_by_text("B G")).to_be_visible()
    expect(page.get_by_role("heading", name="plots found...")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-search-advance-advance-search-result-div-search-list")).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-search-advance-advance-search-result-div-search-list").click()
    expect(page.get_by_text("B G 12 B. Wijaya")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-plots-b20g2012-plot-details-edit-div-cemetery-name-wrapper").get_by_text("Astana Tegal Gundul")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-plots-b20g2012-plot-details-edit-div-main-title").get_by_text("B G 12")).to_be_visible()
    expect(page.get_by_role("button", name="Budi Santoso Wijaya n/a - n/a")).to_be_visible()
