import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://map.chronicle.rip/")
    expect(page.get_by_test_id("toolbar-a-1")).to_be_visible()
    expect(page.get_by_test_id("autocomplete-base-routing-div-search-field")).to_be_visible()
    expect(page.get_by_role("button", name="ADVANCED")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-about-chronicle")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("toolbar-a-mat-focus-indicator").click()
    expect(page.get_by_test_id("login-login-screen-img-logo")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-h2-sign-in-text")).to_be_visible()
    expect(page.get_by_text("Or use Chronicle account")).to_be_visible()
    expect(page.locator("div").filter(has_text=re.compile(r"^Email \*$"))).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Email \*$")).click()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").fill("faris+astanaorg@chronicle.rip")
    expect(page.locator("div").filter(has_text=re.compile(r"^Password \*$"))).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Password \*$")).click()
    page.get_by_test_id("login-mat-form-field-input-password").fill("12345")
    expect(page.get_by_test_id("login-login-screen-div-remember-me").get_by_text("Remember me")).to_be_visible()
    page.get_by_test_id("login-login-screen-div-remember-me").get_by_text("Remember me").click()
    expect(page.get_by_test_id("login-login-screen-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("login-login-screen-button-mat-focus-indicator").click()
    page.goto("https://aus.chronicle.rip/customer-organization/Astana_Tegal_Gundul")
    expect(page.get_by_test_id("customer-organization-chronicle-admin-organization-toolbar-div-business-name-org")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-autocomplete-base-routing-div-search-field")).to_be_visible()
    expect(page.get_by_role("button", name="Advanced")).to_be_visible()
    expect(page.get_by_role("button", name="Astana Tegal Gunduls faris+")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-side-menu-section-sectionId")).to_be_visible()
    expect(page.get_by_role("button", name="Tables")).to_be_visible()
    page.get_by_role("button", name="Tables").click()
    expect(page.get_by_role("button", name="FILTER")).to_be_visible()
    expect(page.get_by_role("button", name="EXPORT")).to_be_visible()
    expect(page.get_by_role("button", name="ADD PLOT")).to_be_visible()
    expect(page.locator("a").filter(has_text="BUSINESS")).to_be_visible()
    expect(page.locator("a").filter(has_text="PERSONS")).to_be_visible()
    expect(page.locator("a").filter(has_text="ROISX")).to_be_visible()
    expect(page.locator("a").filter(has_text="INTERMENTS")).to_be_visible()
    page.locator("a").filter(has_text="INTERMENTS").click()
    expect(page.get_by_role("button", name="ADD INTERMENTS")).to_be_visible()
    expect(page.get_by_role("button", name="EXPORT")).to_be_visible()
    expect(page.get_by_role("button", name="FILTER")).to_be_visible()
    page.get_by_role("button", name="FILTER").click()
    expect(page.get_by_test_id("customer-organization-advance-table-mat-dialog-container-h2-mat-dialog-title")).to_be_visible()
    expect(page.locator("div").filter(has_text=re.compile(r"^Section$")).nth(2)).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Section$")).nth(2).click()
    expect(page.locator("div").filter(has_text=re.compile(r"^Section$")).nth(2)).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Section$")).nth(2).click()
    page.get_by_role("option", name="A").click()
    expect(page.locator("div").filter(has_text=re.compile(r"^Row$")).nth(2)).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Row$")).nth(2).click()
    page.get_by_placeholder("Row").fill("Z")
    expect(page.get_by_role("button", name="APPLY")).to_be_visible()
    page.get_by_role("button", name="APPLY").click()
    expect(page.get_by_test_id("customer-organization-advance-table-mat-sidenav-content-div-table-wrapper").get_by_text("Kirito")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-advance-table-mat-sidenav-content-div-table-wrapper").get_by_text("Kazuto")).to_be_visible()
    page.get_by_role("gridcell", name="Kirito").click()
    expect(page.get_by_role("heading", name="Edit Interment")).to_be_visible()
    expect(page.get_by_role("button", name="Deceased person")).to_be_visible()
    expect(page.get_by_role("heading", name="Interment Applicant")).to_be_visible()
    expect(page.get_by_role("listitem").filter(has_text="Interment ApplicantBapak Budi")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-a20z201-manage-edit-interment-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-a20z201-manage-edit-interment-toolbar-manage-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-a20z201-manage-edit-interment-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-a20z201-manage-edit-interment-toolbar-manage-button-mat-focus-indicator").click()
    expect(page.get_by_role("button", name="Move Interment")).to_be_visible()
    page.get_by_role("button", name="Move Interment").click()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-a20z201-manage-edit-interment-assign-plot-h4-title")).to_be_visible()
    expect(page.locator(".mat-form-field-infix.ng-tns-c122-1336")).to_be_visible()
    page.locator(".mat-form-field-infix.ng-tns-c122-1336").click()
    expect(page.get_by_role("option", name="Astana Tegal Gundul")).to_be_visible()
    page.get_by_role("option", name="Astana Tegal Gundul").click()
    expect(page.get_by_text("AllPlot")).to_be_visible()
    page.get_by_text("AllPlot").click()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-a20z201-manage-edit-interment-input-start-typing-to-search").fill("A Z 2")
    expect(page.get_by_role("option", name="A Z")).to_be_visible()
    page.get_by_role("option", name="A Z").click()
    expect(page.get_by_role("button", name="Assign")).to_be_visible()
    page.get_by_role("button", name="Assign").click()
    page.goto("https://aus.chronicle.rip/customer-organization/advance-table?tab=interments")
    expect(page.get_by_test_id("customer-organization-advance-table-mat-sidenav-content-div-table-wrapper").get_by_text("Kirito")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Kirito")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Kazuto")).to_be_visible()
    expect(page.locator("a").filter(has_text="PLOTS")).to_be_visible()
    page.locator("a").filter(has_text="PLOTS").click()
    expect(page.get_by_role("gridcell", name="A").nth(4)).to_be_visible()
    expect(page.get_by_role("gridcell", name="Z").nth(3)).to_be_visible()
    expect(page.get_by_role("gridcell", name="1").nth(2)).to_be_visible()
    expect(page.locator("mat-row:nth-child(3) > .mat-cell.cdk-cell.cdk-column-interments")).to_be_visible()
    expect(page.get_by_role("gridcell", name="A").nth(1)).to_be_visible()
    expect(page.get_by_role("gridcell", name="Z").nth(1)).to_be_visible()
    expect(page.get_by_role("gridcell", name="2").nth(1)).to_be_visible()
    expect(page.get_by_role("gridcell", name="1").first).to_be_visible()
