import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://map.chronicle.rip/")
    expect(page.get_by_test_id("toolbar-a-1")).to_be_visible()
    expect(page.get_by_role("button", name="ADVANCED")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("toolbar-a-mat-focus-indicator").click()
    expect(page.get_by_test_id("login-login-screen-img-logo")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-h2-sign-in-text")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-div-sign-up-info").get_by_test_id("login-login-screen-a-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-div-under-button").get_by_test_id("login-login-screen-a-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_test_id("login-mat-form-field-input-mat-input-element")).to_be_visible()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").click()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").fill("faris+astanaorg@chronicle.rip")
    expect(page.get_by_test_id("login-mat-form-field-input-password")).to_be_visible()
    page.get_by_test_id("login-mat-form-field-input-password").click()
    page.get_by_test_id("login-mat-form-field-input-password").fill("12345")
    expect(page.locator(".mat-checkbox-inner-container")).to_be_visible()
    page.locator(".mat-checkbox-inner-container").click()
    expect(page.get_by_test_id("login-login-screen-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("login-login-screen-button-mat-focus-indicator").click()
    page.goto("https://aus.chronicle.rip/customer-organization/Astana_Tegal_Gundul")
    expect(page.get_by_test_id("customer-organization-chronicle-admin-organization-toolbar-div-business-name-org")).to_be_visible()
    expect(page.get_by_role("button", name="Advanced")).to_be_visible()
    expect(page.get_by_role("button", name="Astana Tegal Gunduls faris+")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-perfect-scrollbar-button-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-side-menu-section-sectionId")).to_be_visible()
    expect(page.get_by_role("button", name="Tables")).to_be_visible()
    page.get_by_role("button", name="Tables").click()
    expect(page.get_by_test_id("customer-organization-advance-table-select-search-cemetery-div-global-cem-select-label")).to_be_visible()
    expect(page.get_by_role("button", name="ADD PLOT")).to_be_visible()
    expect(page.get_by_role("gridcell", name="B G 13")).to_be_visible()
    page.get_by_role("gridcell", name="B G 13").click()
    expect(page.get_by_role("heading", name="Edit Plot")).to_be_visible()
    expect(page.get_by_role("heading", name="Astana Tegal Gundul - B G")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-plot-edit-span-edit-plot")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-toolbar-manage-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-toolbar-manage-button-mat-focus-indicator").click()
    expect(page.get_by_role("menuitem", name="Edit Plot Id")).to_be_visible()
    page.get_by_role("menuitem", name="Edit Plot Id").click()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-change-plot-id-h4-title")).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-change-plot-id-form-plot-id-form").get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-mat-form-field-input-number").click()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-change-plot-id-form-plot-id-form").get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-mat-form-field-input-number").fill("14")
    expect(page.get_by_role("button", name="Save")).to_be_visible()
    page.get_by_role("button", name="Save").click()
    expect(page.get_by_role("heading", name="Warning")).to_be_visible()
    expect(page.get_by_role("button", name="Proceed")).to_be_visible()
    page.get_by_role("button", name="Proceed").click()
    expect(page.get_by_text("Your changes have been")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-plot-edit-span-edit-plot")).to_be_visible()
    expect(page.get_by_role("button", name="save")).to_be_visible()
    page.get_by_role("button", name="save").click()
    page.goto("https://aus.chronicle.rip/customer-organization/advance-table?tab=plots")
    expect(page.get_by_text("Data saved successfully")).to_be_visible()
    page.get_by_role("button", name="Close").click()
    expect(page.get_by_role("gridcell", name="B G 14")).to_be_visible()
    page.get_by_role("gridcell", name="B G 14").click()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-plot-edit-span-edit-plot")).to_be_visible()
    expect(page.get_by_role("heading", name="Astana Tegal Gundul - B G")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-toolbar-manage-div-13")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-toolbar-manage-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-toolbar-manage-button-mat-focus-indicator").click()
    expect(page.get_by_role("menuitem", name="Edit Plot Id")).to_be_visible()
    page.get_by_role("menuitem", name="Edit Plot Id").click()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-change-plot-id-h4-title")).to_be_visible()
    expect(page.locator("div").filter(has_text=re.compile(r"^Number$")).nth(2)).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-change-plot-id-form-plot-id-form").get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-mat-form-field-input-number").click()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-change-plot-id-form-plot-id-form").get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-mat-form-field-input-number").fill("13")
    expect(page.get_by_role("button", name="Save")).to_be_visible()
    page.get_by_role("button", name="Save").click()
    expect(page.get_by_role("heading", name="Warning")).to_be_visible()
    expect(page.get_by_role("button", name="Proceed")).to_be_visible()
    page.get_by_role("button", name="Proceed").click()
    expect(page.get_by_text("Your changes have been")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-plot-edit-span-edit-plot")).to_be_visible()
    page.get_by_role("button", name="Close").click()
    expect(page.get_by_role("button", name="save")).to_be_visible()
    page.get_by_role("button", name="save").click()
    page.goto("https://aus.chronicle.rip/customer-organization/advance-table?tab=plots")
    expect(page.get_by_text("Data saved successfully")).to_be_visible()
