import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://map.chronicle.rip/")
    expect(page.get_by_test_id("toolbar-a-1")).to_be_visible()
    expect(page.get_by_role("button", name="ADVANCED")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("toolbar-a-mat-focus-indicator").click()
    expect(page.get_by_test_id("login-login-screen-img-logo")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-h2-sign-in-text")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-div-remember-me").get_by_text("Remember me")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-div-under-button").get_by_test_id("login-login-screen-a-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-div-sign-up-info").get_by_test_id("login-login-screen-a-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_test_id("login-mat-form-field-input-mat-input-element")).to_be_visible()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").click()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").fill("faris+astanaorg@chronicle.rip")
    expect(page.get_by_test_id("login-mat-form-field-input-password")).to_be_visible()
    page.get_by_test_id("login-mat-form-field-input-password").click()
    page.get_by_test_id("login-mat-form-field-input-password").fill("12345")
    expect(page.locator(".mat-checkbox-inner-container")).to_be_visible()
    page.locator(".mat-checkbox-inner-container").click()
    expect(page.get_by_test_id("login-login-screen-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("login-login-screen-button-mat-focus-indicator").click()
    page.goto("https://aus.chronicle.rip/customer-organization/Astana_Tegal_Gundul")
    expect(page.get_by_test_id("customer-organization-chronicle-admin-organization-toolbar-div-business-name-org")).to_be_visible()
    expect(page.get_by_role("button", name="Advanced")).to_be_visible()
    expect(page.get_by_role("button", name="Astana Tegal Gunduls faris+")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-side-menu-section-sectionId")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-perfect-scrollbar-button-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_role("button", name="Tables")).to_be_visible()
    page.get_by_role("button", name="Tables").click()
    expect(page.get_by_test_id("customer-organization-advance-table-select-search-cemetery-div-global-cem-select-label")).to_be_visible()
    expect(page.get_by_role("button", name="FILTER")).to_be_visible()
    expect(page.get_by_role("button", name="ADD PLOT")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-advance-table-mat-sidenav-content-div-table-wrapper").get_by_text("A Z 1")).to_be_visible()
    page.get_by_test_id("customer-organization-advance-table-mat-sidenav-content-div-table-wrapper").get_by_text("A Z 1").click()
    page.get_by_role("gridcell", name="A Z 1").click()
    expect(page.get_by_role("heading", name="Edit Plot")).to_be_visible()
    expect(page.get_by_role("heading", name="Astana Tegal Gundul - A Z")).to_be_visible()
    expect(page.locator("div").filter(has_text=re.compile(r"^Burial capacity$")).nth(2)).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-mat-form-field-input-burial-capacity").click()
    expect(page.locator("div").filter(has_text=re.compile(r"^Cremation capacity$")).nth(2)).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-mat-form-field-input-cremation-capacity").click()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-mat-form-field-input-cremation-capacity").fill("2")
    expect(page.get_by_role("button", name="save")).to_be_visible()
    expect(page.get_by_role("button", name="cancel")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-manage-edit-plot-toolbar-manage-button-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_role("button", name="save")).to_be_visible()
    page.get_by_role("button", name="save").click()
    expect(page.get_by_text("Data saved successfully")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-advance-table-mat-sidenav-content-div-table-wrapper").locator("div").filter(has_text=re.compile(r"^2$"))).to_be_visible()
    expect(page.get_by_test_id("customer-organization-advance-table-mat-sidenav-content-div-table-wrapper").get_by_text("A Z 1")).to_be_visible()
