import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://map.chronicle.rip/")
    expect(page.get_by_test_id("toolbar-a-1")).to_be_visible()
    expect(page.get_by_role("button", name="ADVANCED")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("toolbar-a-mat-focus-indicator").click()
    expect(page.get_by_test_id("login-login-screen-img-logo")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-h2-sign-in-text")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-div-under-button").get_by_test_id("login-login-screen-a-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-div-sign-up-info").get_by_test_id("login-login-screen-a-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_test_id("login-mat-form-field-input-mat-input-element")).to_be_visible()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").click()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").fill("faris+astanaorg@chronicle.rip")
    expect(page.get_by_test_id("login-mat-form-field-input-password")).to_be_visible()
    page.get_by_test_id("login-mat-form-field-input-password").click()
    page.get_by_test_id("login-mat-form-field-input-password").fill("12345")
    expect(page.get_by_test_id("login-login-screen-div-remember-me").locator("label")).to_be_visible()
    page.locator(".mat-checkbox-inner-container").click()
    page.get_by_test_id("login-login-screen-button-mat-focus-indicator").click()
    page.goto("https://aus.chronicle.rip/customer-organization/Astana_Tegal_Gundul")
    expect(page.get_by_test_id("customer-organization-chronicle-admin-organization-toolbar-div-business-name-org")).to_be_visible()
    expect(page.get_by_role("button", name="Advanced")).to_be_visible()
    expect(page.get_by_role("button", name="Astana Tegal Gunduls faris+")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-perfect-scrollbar-h3-cemetery-name")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-perfect-scrollbar-button-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-side-menu-section-sectionId")).to_be_visible()
    expect(page.get_by_role("button", name="Tables")).to_be_visible()
    page.get_by_role("button", name="Tables").click()
    expect(page.get_by_text("PLOTS 186")).to_be_visible()
    expect(page.locator("a").filter(has_text="INTERMENTS")).to_be_visible()
    expect(page.locator("a").filter(has_text="ROIS")).to_be_visible()
    expect(page.locator("a").filter(has_text="PERSONS")).to_be_visible()
    expect(page.locator("a").filter(has_text="BUSINESS")).to_be_visible()
    page.locator("a").filter(has_text="INTERMENTS").click()
    expect(page.get_by_text("INTERMENTS 20")).to_be_visible()
    expect(page.get_by_role("gridcell", name="A A 3")).to_be_visible()
    expect(page.get_by_role("gridcell", name="kirito")).to_be_visible()
    expect(page.get_by_role("gridcell", name="saputra", exact=True)).to_be_visible()
    expect(page.get_by_role("gridcell", name="wijaya", exact=True)).to_be_visible()
    page.get_by_role("gridcell", name="A A 3").click()
    expect(page.get_by_role("heading", name="Edit Interment")).to_be_visible()
    expect(page.get_by_role("heading", name="Astana Tegal Gundul - A A")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-interment-edit-form-span-edit-plot")).to_be_visible()
    expect(page.get_by_role("button", name="Deceased person")).to_be_visible()
    page.get_by_role("button", name="Deceased person").click()
    expect(page.get_by_role("textbox", name="First name")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-toolbar-manage-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-toolbar-manage-button-mat-focus-indicator").click()
    expect(page.locator(".cdk-overlay-backdrop")).to_be_visible()
    page.locator(".cdk-overlay-backdrop").click()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-toolbar-manage-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-toolbar-manage-button-mat-focus-indicator").click()
    expect(page.get_by_role("button", name="Delete")).to_be_visible()
    page.get_by_role("button", name="Delete").click()
    expect(page.get_by_role("heading", name="Delete Interment")).to_be_visible()
    expect(page.get_by_role("button", name="DELETE")).to_be_visible()
    page.get_by_role("button", name="DELETE").click()
    expect(page.get_by_role("heading", name="This plot is empty")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-last-interment-dialog-button-no-option")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-last-interment-dialog-button-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_text("Would you like to keep the")).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-last-interment-dialog-button-no-option").click()
    expect(page.get_by_role("menuitem", name="Change to vacant")).to_be_visible()
    page.get_by_role("menuitem", name="Change to vacant").click()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-toolbar-manage-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-a20a203-manage-edit-interment-toolbar-manage-button-mat-focus-indicator").click()
    expect(page.get_by_role("button", name="Delete")).to_be_visible()
    page.get_by_role("button", name="Delete").click()
    expect(page.get_by_role("heading", name="Delete Interment")).to_be_visible()
    expect(page.get_by_role("button", name="DELETE")).to_be_visible()
    page.get_by_role("button", name="DELETE").click()
    page.get_by_test_id("not-found-not-found-button-mat-focus-indicator").click()
