import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://map.chronicle.rip/")
    expect(page.get_by_test_id("toolbar-a-1")).to_be_visible()
    expect(page.get_by_test_id("autocomplete-base-routing-div-search-field")).to_be_visible()
    expect(page.get_by_role("button", name="ADVANCED")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-about-chronicle")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("toolbar-a-mat-focus-indicator").click()
    expect(page.get_by_test_id("login-login-screen-img-logo")).to_be_visible()
    expect(page.get_by_test_id("login-login-screen-h2-sign-in-text")).to_be_visible()
    expect(page.get_by_text("Or use Chronicle account")).to_be_visible()
    expect(page.locator("div").filter(has_text=re.compile(r"^Email \*$"))).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Email \*$")).click()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").fill("faris+astanaorg@chronicle.rip")
    expect(page.locator("div").filter(has_text=re.compile(r"^Password \*$"))).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Password \*$")).click()
    page.get_by_test_id("login-mat-form-field-input-password").fill("12345")
    expect(page.get_by_test_id("login-login-screen-div-remember-me").get_by_text("Remember me")).to_be_visible()
    page.get_by_test_id("login-login-screen-div-remember-me").get_by_text("Remember me").click()
    expect(page.get_by_test_id("login-login-screen-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("login-login-screen-button-mat-focus-indicator").click()
    page.goto("https://aus.chronicle.rip/customer-organization/Astana_Tegal_Gundul")
    expect(page.get_by_test_id("customer-organization-autocomplete-base-routing-div-search-field")).to_be_visible()
    expect(page.get_by_role("button", name="Advanced")).to_be_visible()
    expect(page.get_by_role("button", name="Astana Tegal Gunduls faris+")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-side-menu-section-sectionId")).to_be_visible()
    expect(page.get_by_role("button", name="Tables")).to_be_visible()
    page.get_by_role("button", name="Tables").click()
    expect(page.get_by_role("button", name="FILTER")).to_be_visible()
    expect(page.get_by_role("button", name="EXPORT")).to_be_visible()
    expect(page.get_by_role("button", name="ADD PLOT")).to_be_visible()
    expect(page.locator("a").filter(has_text="BUSINESS")).to_be_visible()
    expect(page.locator("a").filter(has_text="PERSONS")).to_be_visible()
    expect(page.locator("a").filter(has_text="ROISX")).to_be_visible()
    expect(page.locator("a").filter(has_text="INTERMENTS")).to_be_visible()
    page.locator("a").filter(has_text="INTERMENTS").click()
    expect(page.get_by_role("button", name="ADD INTERMENTS")).to_be_visible()
    expect(page.get_by_role("button", name="EXPORT")).to_be_visible()
    expect(page.get_by_role("button", name="FILTER")).to_be_visible()
    page.get_by_role("button", name="FILTER").click()
    expect(page.get_by_test_id("customer-organization-advance-table-mat-dialog-container-h2-mat-dialog-title")).to_be_visible()
    expect(page.locator("div").filter(has_text=re.compile(r"^Section$")).nth(2)).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Section$")).nth(2).click()
    page.locator("div").filter(has_text=re.compile(r"^Section$")).nth(2).click()
    page.get_by_role("option", name="A").click()
    expect(page.locator("div").filter(has_text=re.compile(r"^Row$")).nth(2)).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Row$")).nth(2).click()
    page.get_by_placeholder("Row").fill("z")
    expect(page.get_by_role("button", name="APPLY")).to_be_visible()
    page.get_by_role("button", name="APPLY").click()
    expect(page.get_by_role("gridcell", name="A Z")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Kirito")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Kazuto")).to_be_visible()
    page.get_by_role("gridcell", name="Kirito").click()
    expect(page.get_by_role("heading", name="Edit Interment")).to_be_visible()
    expect(page.get_by_text("Create certificate")).to_be_visible()
    expect(page.get_by_role("button", name="Deceased person")).to_be_visible()
    page.get_by_role("button", name="Deceased person").click()
    expect(page.locator("div").filter(has_text=re.compile(r"^Title$")).nth(2)).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Title$")).nth(2).click()
    page.get_by_role("textbox", name="Title").fill("Mr")
    expect(page.locator(".mat-form-field-infix.ng-tns-c122-1285")).to_be_visible()
    page.locator(".mat-form-field-infix.ng-tns-c122-1285").click()
    expect(page.get_by_role("option", name="Male", exact=True)).to_be_visible()
    page.get_by_role("option", name="Male", exact=True).click()
    expect(page.get_by_role("button", name="Interment details")).to_be_visible()
    page.get_by_role("button", name="Interment details").click()
    expect(page.locator("div").filter(has_text=re.compile(r"^Unit$")).nth(1)).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Unit$")).nth(1).click()
    expect(page.get_by_role("option", name="Centimeters (cm)")).to_be_visible()
    page.get_by_role("option", name="Centimeters (cm)").click()
    expect(page.locator("div").filter(has_text=re.compile(r"^Interment depth$")).nth(2)).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Interment depth$")).nth(2).click()
    page.get_by_role("spinbutton", name="Interment depth").fill("40")
    expect(page.get_by_role("button", name="interment applicant")).to_be_visible()
    page.get_by_role("button", name="interment applicant").click()
    expect(page.get_by_role("button", name="interment applicant")).to_be_visible()
    page.get_by_role("button", name="interment applicant").click()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-a20z201-manage-edit-interment-interment-edit-form-div-applicant-dropdown").get_by_text("Person").click()
    expect(page.locator("div").filter(has_text=re.compile(r"^First name \*$")).nth(5)).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^First name \*$")).nth(5).click()
    expect(page.locator("div").filter(has_text=re.compile(r"^Last name \*$")).nth(5)).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Last name \*$")).nth(5).click()
    page.get_by_role("textbox", name="Last name").fill("wijaya")
    expect(page.locator("div").filter(has_text=re.compile(r"^Last name \*$")).nth(5)).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Last name \*$")).nth(5).click()
    page.get_by_role("textbox", name="Last name").fill("wijaya")
    page.get_by_text("Budi Santoso WijayaJl.").click()
    expect(page.get_by_role("button", name="next of kin")).to_be_visible()
    page.get_by_role("button", name="next of kin").click()
    page.locator("div").filter(has_text=re.compile(r"^Last name \*$")).nth(5).click()
    page.get_by_role("textbox", name="Last name").fill("pratama")
    page.get_by_text("Agus Setiawan PratamaJl.").click()
    expect(page.get_by_role("button", name="funeral minister")).to_be_visible()
    page.get_by_role("button", name="funeral minister").click()
    page.get_by_role("textbox", name="Business name").fill("mas")
    page.get_by_text("Masjid Raya BandungJl. Dago").click()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-a20z201-manage-edit-interment-plus-item-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-a20z201-manage-edit-interment-plus-item-button-mat-focus-indicator").click()
    page.get_by_role("textbox", name="Business name").fill("rumah")
    page.get_by_text("Rumah Duka SejahteraJl. Gatot").click()
    expect(page.get_by_role("button", name="save")).to_be_visible()
    page.get_by_role("button", name="save").click()
    page.goto("https://aus.chronicle.rip/customer-organization/advance-table?tab=interments")
    expect(page.get_by_role("gridcell", name="A Z")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Kirito")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Kazuto")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Male")).to_be_visible()
    expect(page.get_by_role("gridcell", name="40")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Budi Santoso Wijaya")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Agus Setiawan Pratama")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Rumah Duka Sejahtera")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Masjid Raya Bandung")).to_be_visible()
