import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://map.chronicle.rip/")
    expect(page.get_by_test_id("autocomplete-base-routing-div-search-field")).to_be_visible()
    expect(page.get_by_role("button", name="ADVANCED")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-about-chronicle")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("toolbar-a-mat-focus-indicator").click()
    expect(page.get_by_test_id("login-login-screen-h2-sign-in-text")).to_be_visible()
    expect(page.get_by_text("Or use Chronicle account")).to_be_visible()
    expect(page.locator("div").filter(has_text=re.compile(r"^Email \*$"))).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Email \*$")).click()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").fill("faris+astanaorg@chronicle.rip")
    expect(page.locator("div").filter(has_text=re.compile(r"^Password \*$"))).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Password \*$")).click()
    page.get_by_test_id("login-mat-form-field-input-password").fill("12345")
    expect(page.get_by_test_id("login-login-screen-div-remember-me").get_by_text("Remember me")).to_be_visible()
    page.get_by_test_id("login-login-screen-div-remember-me").get_by_text("Remember me").click()
    expect(page.get_by_test_id("login-login-screen-button-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("login-login-screen-button-mat-focus-indicator").click()
    page.goto("https://aus.chronicle.rip/customer-organization/Astana_Tegal_Gundul")
    expect(page.get_by_test_id("customer-organization-autocomplete-base-routing-div-search-field")).to_be_visible()
    expect(page.get_by_role("button", name="Astana Tegal Gunduls faris+")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-side-menu-section-sectionId")).to_be_visible()
    expect(page.get_by_role("button", name="Tables")).to_be_visible()
    page.get_by_role("button", name="Tables").click()
    expect(page.get_by_role("button", name="FILTER")).to_be_visible()
    expect(page.get_by_role("button", name="EXPORT")).to_be_visible()
    expect(page.get_by_role("button", name="ADD PLOT")).to_be_visible()
    expect(page.locator("a").filter(has_text="BUSINESS")).to_be_visible()
    expect(page.locator("a").filter(has_text="PERSONS")).to_be_visible()
    expect(page.locator("a").filter(has_text="ROISX")).to_be_visible()
    expect(page.locator("a").filter(has_text="INTERMENTS")).to_be_visible()
    page.locator("a").filter(has_text="INTERMENTS").click()
    expect(page.get_by_role("button", name="FILTER")).to_be_visible()
    expect(page.get_by_role("button", name="EXPORT")).to_be_visible()
    expect(page.get_by_role("button", name="ADD INTERMENTS")).to_be_visible()
    page.get_by_role("button", name="ADD INTERMENTS").click()
    expect(page.get_by_role("heading", name="Add Interment")).to_be_visible()
    expect(page.get_by_text("AllPlot *")).to_be_visible()
    page.get_by_text("AllPlot *").click()
    page.get_by_test_id("customer-organization-advance-table-manage-add-interment-table-input-start-typing-to-search").fill("a z")
    expect(page.get_by_role("option", name="A Z")).to_be_visible()
    page.get_by_role("option", name="A Z").click()
    expect(page.get_by_role("button", name="Deceased person")).to_be_visible()
    expect(page.get_by_role("textbox", name="First name")).to_be_visible()
    page.get_by_role("textbox", name="First name").click()
    page.get_by_role("textbox", name="First name").fill("Kirito")
    expect(page.get_by_role("textbox", name="Last name")).to_be_visible()
    page.get_by_role("textbox", name="Last name").click()
    page.get_by_role("textbox", name="Last name").fill("Kazuto")
    expect(page.locator(".mat-form-field-infix.ng-tns-c122-1003")).to_be_visible()
    page.locator(".mat-form-field-infix.ng-tns-c122-1003").click()
    expect(page.get_by_role("option", name="Burial")).to_be_visible()
    page.get_by_role("option", name="Burial").click()
    expect(page.get_by_role("button", name="save")).to_be_visible()
    page.get_by_role("button", name="save").click()
    page.goto("https://aus.chronicle.rip/customer-organization/advance-table?tab=interments")
    expect(page.get_by_text("Data saved successfully")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-advance-table-mat-cell-div-mat-tooltip-trigger").nth(2)).to_be_visible()
    page.get_by_role("gridcell", name="A Z").click()
    page.get_by_role("button", name="cancel").click()
    expect(page.get_by_role("gridcell", name="A Z")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Kirito")).to_be_visible()
    expect(page.get_by_role("gridcell", name="Kazuto")).to_be_visible()
