import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://map.chronicle.rip/")
    expect(page.get_by_test_id("toolbar-a-mat-focus-indicator")).to_be_visible()
    page.get_by_test_id("toolbar-a-mat-focus-indicator").click()
    expect(page.get_by_test_id("login-login-screen-h2-sign-in-text")).to_be_visible()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").click()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").fill("faris+astanaorg@chronicle.rip")
    page.get_by_test_id("login-mat-form-field-input-password").click()
    page.get_by_test_id("login-mat-form-field-input-password").fill("12345")
    page.get_by_test_id("login-login-screen-button-mat-focus-indicator").click()
    page.goto("https://aus.chronicle.rip/customer-organization/Astana_Tegal_Gundul")
    expect(page.get_by_role("button", name="Notifications")).to_be_visible()
    page.get_by_role("button", name="Advanced").click()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-advanced-search-form-div-title")).to_be_visible()
    page.get_by_role("combobox", name="Status").locator("span").click()
    page.get_by_role("option", name="Vacant").locator("mat-pseudo-checkbox").click()
    page.locator(".cdk-overlay-backdrop.cdk-overlay-transparent-backdrop").click()
    page.get_by_role("button", name="Plot").click()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-mat-accordion-div-5").get_by_role("button", name="ROI").click()
    page.get_by_role("button", name="Interment", exact=True).click()
    page.get_by_role("button", name="SEARCH").click()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-search-advance-advance-search-result-div-title")).to_be_visible()
    expect(page.locator(".photo").first).to_be_visible()
    expect(page.locator(".plot-label").first).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-search-advance-advance-search-result-div-search-result")).to_contain_text("Vacant")
    page.locator(".plot-label").first.click()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-plots-a20b2010-plot-details-edit-span-plot-status")).to_be_visible()
    expect(page.get_by_role("button", name="Add interment")).to_be_visible()
    page.get_by_role("button", name="Add interment").click()
    expect(page.get_by_role("heading", name="Add Interment")).to_be_visible()
    page.get_by_role("textbox", name="First name").click()
    page.get_by_role("textbox", name="First name").fill("ahmad")
    page.get_by_role("textbox", name="Last name").click()
    page.get_by_role("textbox", name="Last name").fill("faris")
    page.get_by_role("button", name="Deceased person").click()
    page.get_by_role("combobox", name="Interment type").locator("span").click()
    page.get_by_text("Burial").click()
    page.get_by_role("button", name="save", exact=True).click()
    page.goto("https://aus.chronicle.rip/customer-organization/Astana_Tegal_Gundul/plots/A%20B%2010?from=map&zoom=24")
    expect(page.get_by_text("INTERMENTS")).to_be_visible()
    page.locator(".ps__thumb-y").click()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-plots-a20b2010-mat-expansion-panel-button-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-plots-a20b2010-mat-expansion-panel-button-mat-focus-indicator")).to_contain_text("Edit interment")
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-plots-a20b2010-mat-expansion-panel-header-h3-person-full-name").locator("span")).to_contain_text("ahmad faris")
    page.get_by_test_id("customer-organization-astana-tegal-gundul-plots-a20b2010-mat-expansion-panel-button-mat-focus-indicator").click()
    expect(page.get_by_role("heading", name="Edit Interment")).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-a20b2010-manage-edit-interment-toolbar-manage-div-more-btn-wrapper").get_by_test_id("customer-organization-astana-tegal-gundul-a20b2010-manage-edit-interment-toolbar-manage-button-mat-focus-indicator").click()
    page.get_by_role("button", name="Delete").click()
    expect(page.get_by_role("heading", name="Delete Interment")).to_be_visible()
    page.get_by_role("button", name="DELETE").click()
    expect(page.get_by_role("heading", name="This plot is empty")).to_be_visible()
    page.get_by_test_id("customer-organization-astana-tegal-gundul-a20b2010-manage-edit-interment-last-interment-dialog-button-no-option").click()
    expect(page.get_by_role("menuitem", name="Change to vacant")).to_be_visible()
    page.get_by_role("menuitem", name="Change to vacant").click()
    expect(page.get_by_text("Interment record removed")).to_be_visible()
    page.goto("https://aus.chronicle.rip/customer-organization/Astana_Tegal_Gundul/plots/A%20B%2010?from=map&zoom=24")
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-plots-a20b2010-plot-details-edit-span-plot-status")).to_be_visible()
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-plots-a20b2010-plot-details-edit-span-plot-status")).to_contain_text("VACANT")
