import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://map.chronicle.rip/")
    expect(page.get_by_test_id("toolbar-a-1")).to_be_visible()
    expect(page.get_by_role("button", name="ADVANCED")).to_be_visible()
    expect(page.get_by_test_id("toolbar-a-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_role("button", name="3").nth(2)).to_be_visible()
    page.get_by_role("button", name="3").nth(2).click()
    expect(page.get_by_role("button", name="Marker")).to_be_visible()
    page.get_by_role("button", name="Marker").click()
    page.goto("https://map.chronicle.rip/Auckland_Memorial_Park_Cemetery")
    expect(page.locator("h3")).to_be_visible()
    expect(page.get_by_test_id("auckland-memorial-park-cemetery-perfect-scrollbar-button-mat-focus-indicator")).to_be_visible()
    expect(page.get_by_role("button", name="ADVANCED")).to_be_visible()
    page.get_by_role("button", name="ADVANCED").click()
    expect(page.get_by_test_id("auckland-memorial-park-cemetery-advanced-search-form-div-title")).to_be_visible()
    expect(page.get_by_role("button", name="Plot")).to_be_visible()
    page.get_by_role("button", name="Plot").click()
    page.get_by_test_id("auckland-memorial-park-cemetery-mat-form-field-input-number").click()
    page.get_by_text("LVT").click()
    page.locator(".mat-select-placeholder").first.click()
    page.locator(".cdk-overlay-backdrop.cdk-overlay-transparent-backdrop").click()
    page.get_by_test_id("auckland-memorial-park-cemetery-mat-form-field-input-12").fill("12")
    expect(page.get_by_role("button", name="SEARCH")).to_be_visible()
    page.get_by_role("button", name="SEARCH").click()
    expect(page.locator("div").filter(has_text="LVT-J-12|Auckland Memorial").nth(3)).to_be_visible()
    page.locator("div").filter(has_text="LVT-J-12|Auckland Memorial").nth(3).click()
    page.goto("https://map.chronicle.rip/Auckland_Memorial_Park_Cemetery/plots/LVT-J-12?from=map&zoom=24&backTo=%2FAuckland_Memorial_Park_Cemetery%2Fsearch%2Fadvance")
    expect(page.get_by_text("LVT-J-12 J. Chen")).to_be_visible()
    expect(page.get_by_text("Auckland Memorial Park &")).to_be_visible()
    expect(page.get_by_test_id("auckland-memorial-park-cemetery-plots-lvt-j-12-plot-details-public-div-main-title").get_by_text("LVT-J-12")).to_be_visible()
    expect(page.get_by_role("button", name="Jian Hong Chen 21/11/1927 -")).to_be_visible()
