import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://map.chronicle.rip/")
    expect(page.get_by_test_id("toolbar-nav-menu")).to_be_visible()

    page.get_by_test_id("toolbar-a-mat-focus-indicator").click()
    expect(page.get_by_test_id("login-login-screen-h2-sign-in-text")).to_be_visible()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").click()
    page.get_by_test_id("login-mat-form-field-input-mat-input-element").fill("faris+astanaorg@chronicle.rip")
    page.get_by_test_id("login-mat-form-field-input-password").click()
    page.get_by_test_id("login-mat-form-field-input-password").fill("12345")
    page.get_by_test_id("login-login-screen-button-mat-focus-indicator").click()
    page.goto("https://aus.chronicle.rip/customer-organization/Astana_Tegal_Gundul")
    expect(page.get_by_test_id("customer-organization-astana-tegal-gundul-perfect-scrollbar-h3-cemetery-name")).to_be_visible()
    page.get_by_role("button", name="Tables").click()
    expect(page.locator("a").filter(has_text="PERSONS")).to_be_visible()
    page.locator("a").filter(has_text="PERSONS").click()
    expect(page.get_by_role("button", name="ADD PERSON")).to_be_visible()
    page.get_by_role("button", name="ADD PERSON").click()
    expect(page.get_by_test_id("customer-organization-advance-table-manage-add-person-person-add-h1-title-page")).to_be_visible()
    page.get_by_role("textbox", name="First name").click()
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-person-add-div-page-content").click(button="right")
    page.get_by_role("textbox", name="First name").click()
    page.get_by_role("textbox", name="First name").click()
    page.get_by_role("textbox", name="First name").click()
    page.get_by_role("textbox", name="First name").click()
    page.get_by_role("textbox", name="First name").fill("ahmad")
    page.get_by_role("textbox", name="First name").press("Tab")
    page.get_by_role("textbox", name="Last name").fill("faris")
    page.get_by_role("textbox", name="Title").click()
    page.get_by_role("textbox", name="Title").fill("mr")
    page.get_by_role("combobox", name="Gender").locator("span").click()
    expect(page.get_by_text("Female")).to_be_visible()
    page.get_by_text("Male", exact=True).click()
    expect(page.get_by_role("combobox", name="Gender Male")).to_be_visible()

    page.get_by_role("textbox", name="Phone (mobile)").click()
    page.get_by_role("textbox", name="Phone (mobile)").fill("+628962626")
    page.get_by_role("textbox", name="Phone (mobile)").press("ControlOrMeta+a")
    page.get_by_role("textbox", name="Phone (mobile)").press("ControlOrMeta+c")
    page.get_by_role("textbox", name="Phone (mobile)").click()
    page.get_by_role("textbox", name="Phone (mobile)").fill("+6289626261")
    page.get_by_role("textbox", name="Phone (home)").click()
    page.get_by_role("textbox", name="Phone (home)").fill("+6289626262")
    page.get_by_role("textbox", name="Phone (office)").click()
    page.get_by_role("textbox", name="Phone (office)").fill("+6289626263")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").click()
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").fill("faris+chronicle.rip")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").press("ArrowLeft")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").press("ArrowLeft")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").press("ArrowLeft")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").press("ArrowLeft")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").press("ArrowLeft")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").press("ArrowLeft")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").press("ArrowLeft")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").press("ArrowLeft")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").press("ArrowLeft")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").press("ArrowLeft")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").press("ArrowLeft")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").press("ArrowLeft")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").press("ArrowLeft")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-email").fill("faris@chronicle.rip")
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-add-notes").click()
    page.get_by_test_id("customer-organization-advance-table-manage-add-person-mat-form-field-input-add-notes").fill("notes baru")
    page.get_by_role("button", name="save").click()
    expect(page.get_by_role("gridcell", name="ahmad")).to_be_visible()
    expect(page.get_by_role("grid")).to_contain_text("faris")
